version: 2
jobs:
  test:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install --immutable --immutable-cache
      - run:
          name: Run ci checks
          command: npm ci-check

workflows:
  version: 2
  main:
    jobs:
      - test